### PR TITLE
[enh] issuers: do not fetch an identity twice

### PR DESCRIPTION
**Pull request by c-geek**
- Added a dictionary of issuers
- Prefer to browse the dictionary keys, which contains every single issuer only once

### CODE REVIEW

**Comment by M5oul** [comment]
Wow, thanks it's much faster :+1: 
I didn't really understand the modification.

**Comment by c-geek** [comment]
Oh, it's quite simple actually: before my commit, Silkaj was going through `list_issuers` which contained multiple times the same user (because an issuer issued several blocks).

Now with the dictionary, we go through `issuers_dict.keys()` which contains each issuer only once, no matter how much blocks he issued.

**Comment by M5oul** [comment]
Ok, understood.
Data were stored in a `list` and browsed one by one.
Using a `dict` make easily access to all blocks issued by same issuer.

**Comment by c-geek** [comment]
Not the blocks, but the identity! The dict makes the algorithm faster because we don't need to fetch the same identity twice or more times.

**Pull request merged**
