### PR TITLE
Send error to stderr

### PR DESCRIPTION
**Pull request by mmuman**

### CODE REVIEW

**Comment by M5oul** [comment]
Why do you want to send an error when falling back to default node address?
It works, why returning an error?

**Comment by mmuman** [comment]
It's not part of the proper output, it's a warning. If you want to parse the output it's really annoying.

**Comment by M5oul** [comment]
`./sikaj diffi`
and
`./silkaj diffi -p duniter.org:10901`
give `0` to `echo $?` output.

I don't understand the usage of this modification.

**Comment by mmuman** [comment]
I meant parse stdout. From a script or something else.
Like I want to use it with Argos but it will use the warning as menu title instead of the intended name...

**Comment by mmuman** [comment]
Sending stuff to stderr has nothing to do with returning an error code to the shell, btw.

**Comment by M5oul** [comment]
Ok. Let's merge.

**Pull request merged**
